### ISSUE TITLE
Import does not import filters by default.

### ISSUE THREAD

**Issue by mdeweerd** [INTI-CMNB/KiBot#114]
It seems that 'filters' are not imported as the  [documentation indicates](https://github.com/INTI-CMNB/KiBot/blob/27b26feb88f2b0dd4fbf5a9f50bbd9387aace7ab/README.md?plain=1#L1832)

The attached test case suggests that filters are not imported.
```
kibot -e tests/board_samples/kicad_5/kibom-variant_4.sch -b tests/board_samples/kicad_5/kibom-variant_4.kicad_pcb -c tests/yaml_samples/step_variant_2.kibot.yaml -g variant=topvariant JLCPCB_bom
```

[tc2.tar.gz](https://github.com/INTI-CMNB/KiBot/files/7577183/tc2.tar.gz)

**Comment by set-soft** [comment]
Thanks @mdeweerd !
The problem was when you tried to import filters from multiple files.

**Comment by bob-swinkels** [comment]
Is there a way to circumvent this problem at the moment, or is it best to duplicate the filters to the "master" file?

**Comment by mdeweerd** [comment]
@bob-swinkels This was fixed.  I had duplicated the filters to the master file, but removed them after the fix and this works.

**Comment by bob-swinkels** [comment]
Thank you @mdeweerd. Should this now also work with the current setsoft/kicad_auto:dev because I still experience this problem when using this image.

**Comment by bob-swinkels** [comment]
My bad, it does actually work :)
